name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # For manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
            cd ${{ secrets.DEPLOY_PATH }}
            sudo chown -R ${{ secrets.EC2_USERNAME }}:${{ secrets.EC2_USERNAME }} .
            git pull origin main
          "
